// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetCommentLikes(ctx context.Context, arg GetCommentLikesParams) ([]uuid.UUID, error)
	GetCommentLikesCount(ctx context.Context, commentID int32) (int64, error)
	GetPostLikes(ctx context.Context, arg GetPostLikesParams) ([]uuid.UUID, error)
	GetPostLikesCount(ctx context.Context, postID int32) (int64, error)
	LikeComment(ctx context.Context, arg LikeCommentParams) (CommentLike, error)
	LikePost(ctx context.Context, arg LikePostParams) (PostLike, error)
	UnlikeComment(ctx context.Context, arg UnlikeCommentParams) (CommentLike, error)
	UnlikePost(ctx context.Context, arg UnlikePostParams) (PostLike, error)
}

var _ Querier = (*Queries)(nil)
