// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int32          `json:"id"`
	Username  string         `json:"username"`
	Uniqueid  string         `json:"uniqueid"`
	Age       int32          `json:"age"`
	Bio       sql.NullString `json:"bio"`
	Avatar    sql.NullString `json:"avatar"`
	Status    string         `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
