// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Post struct {
	ID        int32           `json:"id"`
	UniqueID  uuid.UUID       `json:"unique_id"`
	CreatedAt sql.NullTime    `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
	Url       string          `json:"url"`
	Caption   sql.NullString  `json:"caption"`
	Lat       sql.NullFloat64 `json:"lat"`
	Lng       sql.NullFloat64 `json:"lng"`
}
