// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	DeletePost(ctx context.Context, id int32) error
	DeletePostsByUniqueId(ctx context.Context, uniqueID uuid.UUID) error
	GetPost(ctx context.Context, id int32) (GetPostRow, error)
	GetPosts(ctx context.Context, arg GetPostsParams) ([]GetPostsRow, error)
	GetPostsByUniqueId(ctx context.Context, uniqueID uuid.UUID) ([]GetPostsByUniqueIdRow, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
