// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID           int32     `json:"id"`
	PostID       int32     `json:"post_id"`
	UserUniqueID uuid.UUID `json:"user_unique_id"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"created_at"`
}
