// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	DeleteComment(ctx context.Context, id int32) error
	GetComments(ctx context.Context, arg GetCommentsParams) ([]Comment, error)
	GetCommentsCount(ctx context.Context, postID int32) (int64, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
}

var _ Querier = (*Queries)(nil)
