// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Follower struct {
	ID               int32     `json:"id"`
	LeaderUniqueID   uuid.UUID `json:"leader_unique_id"`
	FollowerUniqueID uuid.UUID `json:"follower_unique_id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
