// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	FollowUser(ctx context.Context, arg FollowUserParams) (Follower, error)
	UnfollowUser(ctx context.Context, arg UnfollowUserParams) (Follower, error)
}

var _ Querier = (*Queries)(nil)
