// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: account.sql

package db

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO "accounts" (
  "email",
  "username",
  "avatar",
  "age",
  "bio",
  "status"
)
VALUES(
    $1,$2,$3,$4,$5,$6
) 
RETURNING id, username, email, unique_id, age, gender, bio, avatar, status, created_at, updated_at
`

type CreateAccountParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Age      int32  `json:"age"`
	Bio      string `json:"bio"`
	Status   string `json:"status"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Email,
		arg.Username,
		arg.Avatar,
		arg.Age,
		arg.Bio,
		arg.Status,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.UniqueID,
		&i.Age,
		&i.Gender,
		&i.Bio,
		&i.Avatar,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccountByUniqueID = `-- name: DeleteAccountByUniqueID :exec
DELETE FROM "accounts"
WHERE "unique_id" = $1
`

func (q *Queries) DeleteAccountByUniqueID(ctx context.Context, uniqueID string) error {
	_, err := q.db.ExecContext(ctx, deleteAccountByUniqueID, uniqueID)
	return err
}

const getAccountByUniqueID = `-- name: GetAccountByUniqueID :one
SELECT id, username, email, unique_id, age, gender, bio, avatar, status, created_at, updated_at
FROM "accounts"
WHERE "unique_id" = $1
`

func (q *Queries) GetAccountByUniqueID(ctx context.Context, uniqueID string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUniqueID, uniqueID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.UniqueID,
		&i.Age,
		&i.Gender,
		&i.Bio,
		&i.Avatar,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE "accounts"
SET
    "username" = coalesce($2, username),
    "avatar" = coalesce($3, avatar),
    "age" = coalesce($4, age),
    "bio" = coalesce($5, bio),
    "status" = coalesce($6, status)
WHERE "unique_id" = $1
RETURNING id, username, email, unique_id, age, gender, bio, avatar, status, created_at, updated_at
`

type UpdateAccountParams struct {
	UniqueID string         `json:"unique_id"`
	Username sql.NullString `json:"username"`
	Avatar   sql.NullString `json:"avatar"`
	Age      sql.NullInt32  `json:"age"`
	Bio      sql.NullString `json:"bio"`
	Status   sql.NullString `json:"status"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.UniqueID,
		arg.Username,
		arg.Avatar,
		arg.Age,
		arg.Bio,
		arg.Status,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.UniqueID,
		&i.Age,
		&i.Gender,
		&i.Bio,
		&i.Avatar,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
